FROM alpine:latest

LABEL opensciencegrid.name="Minimal"
LABEL opensciencegrid.description="Minimal image - used for testing"
LABEL opensciencegrid.url="https://osg-htc.org/"
LABEL opensciencegrid.category="Tools"
LABEL opensciencegrid.definition_url="https://github.com/osg-htc/htc-images"

