FROM alpine:latest

LABEL opensciencegrid.name="Minimal + Python"
LABEL opensciencegrid.description="Minimal image with Python - used for testing"
LABEL opensciencegrid.url="https://osg-htc.org/"
LABEL opensciencegrid.category="Tools"
LABEL opensciencegrid.definition_url="https://github.com/osg-htc/htc-images"

RUN apk update && apk add bash python3

